server:
  port: 17451

spring:
  # datasource 数据源配置内容
  datasource:
    url: jdbc:mysql://localhost:3306/hello?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  # JPA 配置内容，对应 JpaProperties 类
  jpa:
    show-sql: true # 打印 SQL[生产环境，建议关闭]
    # Hibernate 配置内容，对应 HibernateProperties 类
    hibernate: # [实际项目无需配置 hibernate 配置项]
      # <jpa 的 hibernate.ddl-auto 的几个属性值区别>
      # none: 无
      # create ：每次加载 hibernate 时都会删除上一次的生成的表，然后根据你的 model 类再重新来生成新表，哪怕两次没有任何改变也要这样执行，这就是导致数据库表数据丢失的一个重要原因。
      # create-drop ：每次加载 hibernate 时根据 model 类生成表，但是 sessionFactory 一关闭，表就自动删除。
      # update ：最常用的属性，第一次加载 hibernate 时根据 model 类会自动建立起表的结构（前提是先建立好数据库），以后加载 hibernate 时根据 model 类自动更新表结构，即使表结构改变了但表中的行仍然存在不会删除以前的行。要注意的是当部署到服务器后，表结构是不会被马上建立起来的，是要等应用第一次运行起来后才会。
      # validate ：每次加载 hibernate 时，验证创建数据库表结构，只会和数据库中的表进行比较，不会创建新表，但是会插入新值。 * 建议，生产环境下，建议配置 none ，不使用 Hibernate Auto DDL 功能
      ddl-auto: none

