server:
  port: 17450

spring:
  # datasource 数据源配置内容
  datasource:
    url: jdbc:mysql://localhost:3306/hello?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

# mybatis 配置内容
mybatis:
  #config-location: classpath:mybatis-config.xml # 配置 MyBatis 配置文件路径
  configuration:
    map-underscore-to-camel-case: true # 使用驼峰命名法转换字段
  mapper-locations: classpath*:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: com.open.orm.mybatis.dataobject # 配置数据库实体包路径

# logging
logging:
  level:
    com:
      open:
        orm:
          mybatis:
            mapper: debug
